import type { Cluster } from './cluster.js';
import type { Category } from './types.js';
import type { Tldr } from './tldr.js';

const SECTION_ORDER: Category[] = ['code', 'community', 'blog', 'news', 'research', 'video'];
const SECTION_LABELS: Record<Category, string> = {
  code: 'Claude Code / Releases / Repos',
  community: 'Hacker News & Community',
  blog: 'Engineering Blogs',
  news: 'News',
  research: 'Research (arXiv)',
  video: 'Videos',
};

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function uniq<T>(arr: T[]): T[] {
  return Array.from(new Set(arr));
}

function renderTldr(tldr: Tldr | null): string {
  if (!tldr || !tldr.bullets.length) return '';
  const items = tldr.bullets.map(b => `<li style="margin-bottom:6px;line-height:1.45">${esc(b)}</li>`).join('');
  return `<div style="background:#fff8e1;border-left:4px solid #f5a623;padding:14px 18px;margin-top:18px;border-radius:4px">
    <div style="font-size:11px;letter-spacing:1px;text-transform:uppercase;color:#b07a00;font-weight:700;margin-bottom:8px">TL;DR</div>
    <ul style="margin:0;padding-left:20px;font-size:14px;color:#222">${items}</ul>
  </div>`;
}

export function render(clusters: Cluster[], tldr: Tldr | null): { html: string; text: string; subject: string } {
  const date = new Date().toISOString().slice(0, 10);
  const bySection = new Map<Category, Cluster[]>();
  for (const c of clusters) {
    const cat = c.primary.category;
    if (!bySection.has(cat)) bySection.set(cat, []);
    bySection.get(cat)!.push(c);
  }

  const sectionsHtml = SECTION_ORDER
    .filter(k => bySection.has(k))
    .map(k => {
      const items = bySection.get(k)!
        .map(c => {
          const h = c.primary.llmHeadline || c.primary.title;
          const s = c.primary.llmSummary || c.primary.summary || '';
          const why = c.primary.llmWhy
            ? `<div style="color:#555;font-size:13px;margin-top:6px"><em>Why it matters:</em> ${esc(c.primary.llmWhy)}</div>`
            : '';
          const sources = uniq(c.items.map(i => i.source)).join(' · ');
          return `<li style="margin-bottom:18px;padding-bottom:14px;border-bottom:1px solid #f0f0f0">
            <a href="${esc(c.primary.url)}" style="color:#0b66c3;text-decoration:none;font-weight:600;font-size:15px">${esc(h)}</a>
            <div style="color:#222;font-size:14px;margin-top:6px;line-height:1.45">${esc(s)}</div>
            ${why}
            <div style="color:#888;font-size:12px;margin-top:6px">${esc(sources)}</div>
          </li>`;
        })
        .join('');
      return `<h2 style="font-size:15px;text-transform:uppercase;letter-spacing:0.5px;color:#444;border-bottom:2px solid #0b66c3;padding-bottom:4px;margin-top:28px">${SECTION_LABELS[k]}</h2><ul style="list-style:none;padding:0;margin:12px 0 0">${items}</ul>`;
    })
    .join('');

  const total = clusters.length;
  const html = `<!doctype html><html><body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;max-width:680px;margin:0 auto;padding:24px;color:#111;background:#fff">
<h1 style="font-size:22px;margin:0">AI Digest — ${date}</h1>
<p style="color:#666;margin:4px 0 0;font-size:13px">${total} stories across ${bySection.size} sections · tailored for Claude Code / engineering</p>
${renderTldr(tldr)}
${sectionsHtml}
<hr style="border:none;border-top:1px solid #eee;margin-top:36px">
<p style="color:#999;font-size:11px">Generated by ai-news-digest</p>
</body></html>`;

  const tldrText = tldr && tldr.bullets.length
    ? `TL;DR\n${tldr.bullets.map(b => `  • ${b}`).join('\n')}\n\n`
    : '';
  const text = tldrText + SECTION_ORDER
    .filter(k => bySection.has(k))
    .map(k => {
      const body = bySection.get(k)!
        .map(c => `- ${c.primary.llmHeadline || c.primary.title}\n  ${c.primary.url}`)
        .join('\n');
      return `## ${SECTION_LABELS[k]}\n${body}`;
    })
    .join('\n\n');

  const subject = `AI Digest ${date} — ${total} stories`;
  return { html, text, subject };
}
